version: '3.5'
services:

  maestro1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: maestro1
    environment:
      - node.name=maestro1
      - cluster.name=cluster-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
      - discovery.seed_hosts= maestro2,data1,data2,ingesta1,ingesta2,coordinador1
      - cluster.initial_master_nodes= maestro1,maestro2
      - node.master=true 
      - node.voting_only=false 
      - node.data=false 
      - node.ingest=false 
      - cluster.remote.connect=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      
  maestro2:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
      container_name: maestro2
      environment:
        - node.name=maestro2
        - cluster.name=cluster-es
  #      - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
        - discovery.seed_hosts= maestro1,maestro2,data1,data2,ingesta1,ingesta2,coordinador1
        - cluster.initial_master_nodes= maestro1,maestro2
        - node.master=true 
        - node.voting_only=false 
        - node.data=false 
        - node.ingest=false 
        - cluster.remote.connect=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data02:/usr/share/elasticsearch/data
  
  data1:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
      container_name: data1
      environment:
        - node.name=data1
        - cluster.name=cluster-es
  #      - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
        - discovery.seed_hosts= maestro1,maestro2,data1,data2,ingesta1,ingesta2,coordinador1
        - cluster.initial_master_nodes= maestro1,maestro2
        - node.master=true 
        - node.voting_only=true 
        - node.data=true 
        - node.ingest=false 
        - cluster.remote.connect=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data03:/usr/share/elasticsearch/data
  data2:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
      container_name: data2
      environment:
        - node.name=data2
        - cluster.name=cluster-es
    #    - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
        - discovery.seed_hosts= maestro1,maestro2,data1,data2,ingesta1,ingesta2,coordinador1
        - cluster.initial_master_nodes= maestro1,maestro2
        - node.master=false 
        - node.voting_only=false 
        - node.data=true 
        - node.ingest=false 
        - cluster.remote.connect=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data04:/usr/share/elasticsearch/data
        
  ingesta1:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
      container_name: ingesta1
      environment:
        - node.name=ingesta1
        - cluster.name=cluster-es
  #      - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
        - discovery.seed_hosts= maestro1,maestro2,data1,data2,ingesta1,ingesta2,coordinador1
        - cluster.initial_master_nodes= maestro1,maestro2
        - node.master=false 
        - node.voting_only=false 
        - node.data=false 
        - node.ingest=true 
        - cluster.remote.connect=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data05:/usr/share/elasticsearch/data
  
  ingesta2:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
      container_name: ingesta2
      environment:
        - node.name=ingesta2
        - cluster.name=cluster-es
  #      - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
        - discovery.seed_hosts= maestro1,maestro2,data1,data2,ingesta1,ingesta2,coordinador1
        - node.master=false 
        - node.voting_only=false 
        - node.data=false 
        - node.ingest=true 
        - cluster.remote.connect=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data06:/usr/share/elasticsearch/data
  coordinador1:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
      container_name: coordinador1
      environment:
        - node.name=coordinador1
        - cluster.name=cluster-es
  #      - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
        - discovery.seed_hosts= maestro1,maestro2,data1,data2,ingesta1,ingesta2,coordinador1
        - node.master=false 
        - node.voting_only=false 
        - node.data=false 
        - node.ingest=false 
        - cluster.remote.connect=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data07:/usr/share/elasticsearch/data
        
  cerebro:
    image: lmenezes/cerebro:0.8.5
    container_name: cerebro
    volumes:
      - ./application.conf:/opt/cerebro/conf/application.conf

 # kibana:
#    image: docker.elastic.co/kibana/kibana:7.5.2
#    container_name: kibana
#    environment:
#      ELASTICSEARCH_HOSTS: "http://nginx:8082"
#      SERVER_NAME: "kibana"
#      SERVER_HOST: "kibana"
#      ELASTICSEARCH_USERNAME: "elastic"
#      ELASTICSEARCH_PASSWORD: "password"

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_error.log:/etc/nginx/error_log.log
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      
volumes:
  data01:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data01'
  data02:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data02'
  data03:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data03'
  data04:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data04'
  data05:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data05'
  data06:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data06'
  data07:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data07'
