version: '3.5'
services:
  maestro1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: maestro1
    environment:
      - node.name=maestro1
      - cluster.name=cluster-es
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=maestro1,maestro2,data1,data2,data3,data4,ingesta1,ingesta2,coordinador1
      - cluster.initial_master_nodes=maestro1,maestro2
      - "ES_JAVA_OPTS=-Xms140m -Xmx140m"
      - node.master=true
      - node.voting_only=false
      - node.data=false
      - node.ingest=false
      #- node.remote_cluster_client=false  # 
      - cluster.remote.connect=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - backnet
      
  maestro2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: maestro2
    environment:
      - node.name=maestro2
      - cluster.name=cluster-es
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=maestro1,maestro2,data1,data2,data3,data4,ingesta1,ingesta2,coordinador1
      - cluster.initial_master_nodes=maestro1,maestro2
      - "ES_JAVA_OPTS=-Xms140m -Xmx140m"
      - node.master=true
      - node.voting_only=false
      - node.data=false
      - node.ingest=false
      # - node.remote_cluster_client=false  # 
      - cluster.remote.connect=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - backnet

  data1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: data1
    environment:
      - node.name=data1
      - cluster.name=cluster-es
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=maestro1,maestro2,data1,data2,data3,data4,ingesta1,ingesta2,coordinador1
      - cluster.initial_master_nodes=maestro1,maestro2
      - "ES_JAVA_OPTS=-Xms140m -Xmx140m"
      - node.master=true
      - node.voting_only=true
      - node.data=true
      - node.ingest=false
      #- node.remote_cluster_client=false  #
      - cluster.remote.connect=false 
      - node.attr.tamano=big
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - backnet

  data2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: data2
    environment:
      - node.name=data2
      - cluster.name=cluster-es
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=maestro1,maestro2,data1,data2,data3,data4,ingesta1,ingesta2,coordinador1
      - "ES_JAVA_OPTS=-Xms140m -Xmx140m"
      - node.master=false
      - node.voting_only=false
      - node.data=true
      - node.ingest=false
      #- node.remote_cluster_client=false  #
      - cluster.remote.connect=false
      - node.attr.tamano=big
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data04:/usr/share/elasticsearch/data
    networks:
      - backnet
 
  data3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: data3
    environment:
      - node.name=data3
      - cluster.name=cluster-es
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=maestro1,maestro2,data1,data2,data3,data4,ingesta1,ingesta2,coordinador1
      - "ES_JAVA_OPTS=-Xms140m -Xmx140m"
      - node.master=false
      - node.voting_only=false
      - node.data=true
      - node.ingest=false
      #- node.remote_cluster_client=false  #
      - cluster.remote.connect=false
      - node.attr.tamano=small
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data05:/usr/share/elasticsearch/data
    networks:
      - backnet

  data4:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: data4
    environment:
      - node.name=data4
      - cluster.name=cluster-es
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=maestro1,maestro2,data1,data2,data3,data4,ingesta1,ingesta2,coordinador1
      - "ES_JAVA_OPTS=-Xms140m -Xmx140m"
      - node.master=false
      - node.voting_only=false
      - node.data=true
      - node.ingest=false
      #- node.remote_cluster_client=false  #
      - cluster.remote.connect=false
      - node.attr.tamano=small
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data06:/usr/share/elasticsearch/data
    networks:
      - backnet

  ingesta1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: ingesta1
    environment:
      - node.name=ingesta1
      - cluster.name=cluster-es
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=maestro1,maestro2,data1,data2,data3,data4,ingesta1,ingesta2,coordinador1
      - "ES_JAVA_OPTS=-Xms140m -Xmx140m"
      - node.master=false
      - node.voting_only=false
      - node.data=false
      - node.ingest=true
      - transport.host=_eth0_
      #- node.remote_cluster_client=false  #
      - cluster.remote.connect=false 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data07:/usr/share/elasticsearch/data
    networks:
      - backnet
      - frontnet

  ingesta2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: ingesta2
    environment:
      - node.name=ingesta2
      - cluster.name=cluster-es
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=maestro1,maestro2,data1,data2,data3,data4,ingesta1,ingesta2,coordinador1
      - "ES_JAVA_OPTS=-Xms140m -Xmx140m"
      - node.master=false
      - node.voting_only=false
      - node.data=false
      - node.ingest=true
      - transport.host=_eth0_
      #- node.remote_cluster_client=false  #
      - cluster.remote.connect=false 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data08:/usr/share/elasticsearch/data
    networks:
      - backnet # eth0
      - frontnet # eth1

  coordinador1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: coordinador1
    environment:
      - node.name=coordinador1
      - cluster.name=cluster-es
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=maestro1,maestro2,data1,data2,data3,data4,ingesta1,ingesta2,coordinador1
      - "ES_JAVA_OPTS=-Xms140m -Xmx140m"
      - node.master=false
      - node.voting_only=false
      - node.data=false
      - node.ingest=false
      - transport.host=_eth0_
      #- node.remote_cluster_client=false  #
      - cluster.remote.connect=false 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data09:/usr/share/elasticsearch/data
    networks:
      - backnet
      - frontnet

  cerebro:
    image: lmenezes/cerebro:0.8.5
    container_name: cerebro
    volumes:
      - ./application.conf:/opt/cerebro/conf/application.conf
    networks:
      - frontnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "http://nginx:8082"
      SERVER_NAME: "kibana"
      SERVER_HOST: "kibana"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "password"
    networks:
      - frontnet

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_error.log:/etc/nginx/error_log.log
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    networks:
      - frontnet
      - publicnet
      
volumes:
  data01:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data01'
  data02:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data02'
  data03:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data03'
  data04:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data04'
  data05:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data05'
  data06:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data06'
  data07:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data07'
  data08:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data08'
  data09:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/elasticsearch/data09'    
networks:
  backnet:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/8

  frontnet:
    ipam:
      driver: default
      config:
        - subnet: 20.10.0.0/8

  publicnet:
    ipam:
      driver: default
      config:
        - subnet: 30.10.0.0/8